export const ENV = {
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '',
  GOOGLE_OAUTH_EXPO_WEB_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID || '',
  GOOGLE_OAUTH_EXPO_IOS_CLIENT_ID:
    process.env.EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID || '',
}
